version: '3.7'
networks:
  cluster_net:
    external: true
    name: siesta-net

services:
  funnel:
    build: .
    stdin_open: true
    environment:
      master.uri: local[*]
      database: s3 # cassandra-rdd or s3
      #for s3 (minio)
      s3.endpoint: http://minio:9000
      s3.user: minioadmin
      s3.key: minioadmin
      s3.timetout: 600000
      #for cassandra
      cassandra.max_requests_per_local_connection: 32768
      cassandra.max_requests_per_remote_connection: 22000
      cassandra.connections_per_host: 1000
      cassandra.max_queue_size: 1024
      cassandra.connection_timeout: 30000
      cassandra.read_timeout: 30000
      spring.data.cassandra.contact-points: cassandra
      spring.data.cassandra.port: 9042
      spring.data.cassandra.user: cassandra
      spring.data.cassandra.password: cassandra
      server.port: 8090 # port of the application
    volumes:
      - ./build:/root/.m2
    ports:
      - '8090:8090'
    networks:
      - cluster_net
