version: '3.7'
networks:
  cluster_net:
    external: true
    name: siesta-net

services:
  funnel:
    build: .
    stdin_open: true
    environment:
      master.uri: local[*]
      database: s3 # cassandra-rdd or s3
      delta: true # True for streaming, False for batching
      #for s3 (minio)
      s3.endpoint: http://minio:9000
      s3.user: minioadmin
      s3.key: minioadmin
      s3.timeout: 600000
      #for cassandra
      cassandra.max_requests_per_local_connection: 32768
      cassandra.max_requests_per_remote_connection: 22000
      cassandra.connections_per_host: 1000
      cassandra.max_queue_size: 1024
      cassandra.connection_timeout: 30000
      cassandra.read_timeout: 30000
      spring.data.cassandra.contact-points: cassandra
      spring.data.cassandra.port: 9042
      spring.data.cassandra.user: cassandra
      spring.data.cassandra.password: cassandra
      server.port: 8090 # port of the application
    volumes:
      - ./build:/root/.m2
    ports:
      - '8090:8090'
    networks:
      - cluster_net

#  spark-master:
#    image: bitnami/spark:3.5.4
#    container_name: spark-master
#    environment:
#      - SPARK_MODE=master
#      - SPARK_RPC_AUTHENTICATION_ENABLED=no
#      - SPARK_RPC_ENCRYPTION_ENABLED=no
#      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
#      - SPARK_SSL_ENABLED=no
#    ports:
#      - "7077:7077" # Spark master port
#      - "8080:8080" # Spark Web UI
#    networks:
#      - cluster_net
#
#  spark-worker-1:
#    image: bitnami/spark:3.5.4
#    container_name: spark-worker-1
#    environment:
#      - SPARK_MODE=worker
#      - SPARK_MASTER_URL=spark://spark-master:7077
#      - SPARK_WORKER_MEMORY=1G
#      - SPARK_WORKER_CORES=1
#    depends_on:
#      - spark-master
#    networks:
#      - cluster_net
#
#  spark-worker-2:
#    image: bitnami/spark:3.5.4
#    container_name: spark-worker-2
#    environment:
#      - SPARK_MODE=worker
#      - SPARK_MASTER_URL=spark://spark-master:7077
#      - SPARK_WORKER_MEMORY=1G
#      - SPARK_WORKER_CORES=1
#    depends_on:
#      - spark-master
#    networks:
#      - cluster_net
